// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3CallZrlhD5GXSYQlYTVUUv6x6yVX5Dg',
    appId: '1:868077407506:web:cbefdc8b40471e53a977cb',
    messagingSenderId: '868077407506',
    projectId: 'pokemonapp-sastaticket',
    authDomain: 'pokemonapp-sastaticket.firebaseapp.com',
    storageBucket: 'pokemonapp-sastaticket.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClqR6GDrWBKIVcUJu9lHTwx_m42KC7LUg',
    appId: '1:868077407506:android:f163a24bac8d75daa977cb',
    messagingSenderId: '868077407506',
    projectId: 'pokemonapp-sastaticket',
    storageBucket: 'pokemonapp-sastaticket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlCZecABGn9XoAOFI82DKeWbXGJVtnkow',
    appId: '1:868077407506:ios:11383ea5e339093ba977cb',
    messagingSenderId: '868077407506',
    projectId: 'pokemonapp-sastaticket',
    storageBucket: 'pokemonapp-sastaticket.appspot.com',
    iosClientId: '868077407506-qtndsidckdp9j8s5p56s1f6lhojp0gds.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokemonAppSastaticket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlCZecABGn9XoAOFI82DKeWbXGJVtnkow',
    appId: '1:868077407506:ios:9b2ed37c7d30b672a977cb',
    messagingSenderId: '868077407506',
    projectId: 'pokemonapp-sastaticket',
    storageBucket: 'pokemonapp-sastaticket.appspot.com',
    iosClientId: '868077407506-8ouhvltlknc5k6urjh3pe1i96qsldlk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokemonAppSastaticket.RunnerTests',
  );
}
